### ISSUE TITLE
2.5.0 bug "Uncaught TypeError: Cannot read property 'trigger' of undefined"

### ISSUE THREAD

**Issue by spiritius** [NikolayRys/Likely#190] opened 2020-09-03 18:54 UTC
Hello.

I see a bug on my [test page](https://spiritius.net/temp/beauty_masters/_test.html) and on https://ilyabirman.ru/projects/likely/ too.
Like this one:

`core.js?1373299112:13 Uncaught TypeError: Cannot read property 'trigger' of undefined
    at Object.updateCount (core.js?1373299112:13)
    at dk?st.cmd=extLike&ref=https%3A%2F%2Filyabirman.ru%2Fprojects%2Flikely%2F&uid=0:1`

Can somebody explain me what I need to do? :) 
Thanks!

**Comment by NikolayRys** [comment] 2020-09-03 18:56
Thanks for your feedback, I'll check it out

**Comment by spiritius** [comment] 2020-09-03 19:59
When you add `data-counters="no"` to `<div class="likely">` there is no error.
Apparently it relates to ok.ru repost counter.

**Comment by levbarkov** [comment] 2020-09-04 09:49
same issue. 

`When you add data-counters="no" to <div class="likely">` - no help

**Comment by NikolayRys** [comment] 2020-09-04 13:46
@levbarkov, @spiritius 
Okay, It's caused by OK(odnoklassniki) counter, it'll be fixed in the 2.6 release in the coming days

**Comment by NikolayRys** [comment] 2020-10-26 03:19
Please install 2.6, it has been fixed there:
https://github.com/NikolayRys/Likely/releases/tag/v2.6
or
https://www.npmjs.com/package/ilyabirman-likely/v/2.6.0

**Closed by NikolayRys** 2020-10-26 03:19 UTC
